{
 "title": "jmx-exporter-dashboard",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per release > pod",
 "tags": [ "JVM" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(jvm_info{namespace=\"$namespace\"},pod_name)"
    }
   },
   { "name": "interval", "label": "interval", "query": "30s" }
  ]
 },
 "panels": [
  {
   "title": "Avg. response time",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (label,target)(rate(resp_time_sum[$interval]) / (rate(resp_time_count[$interval])>0))",
     "legendFormat": " {{label}} {{target}}"
    }
   ]
  },
  {
   "title": "Response Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(resp_time_count[$interval])",
     "legendFormat": "{{label}}  {{target}}"
    }
   ]
  },
  {
   "title": "Pct response times",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(resp_time) by (label,quantile)",
     "legendFormat": "{{label}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Process Cpu Load",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{pod_name=~\"$pod\", namespace=~\"$namespace\"}*100 ",
     "legendFormat": "CPU - {{job}} "
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",pod_name=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Used - {{job}} {{pod_name}}"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",pod_name=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Max - {{job}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",pod_name=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Used - {{job}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "G1 Eden Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=~\"$namespace\", pool=\"G1 Eden Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Max - {{job}} {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=~\"$namespace\", pool=\"G1 Eden Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Used - {{job}} {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=~\"$namespace\", pool=\"G1 Eden Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Committed - {{job}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "G1 Old Gen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=~\"$namespace\", pool=\"G1 Old Gen\",pod_name=~\"$pod\"}",
     "legendFormat": "Max - {{job}} {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=~\"$namespace\", pool=\"G1 Old Gen\",pod_name=~\"$pod\"}",
     "legendFormat": "Used - {{job}} {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=~\"$namespace\", pool=\"G1 Old Gen\",pod_name=~\"$pod\"}",
     "legendFormat": "Committed - {{job}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "G1 Survivor Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=~\"$namespace\", pool=\"G1 Survivor Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Max - {{job}} {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=~\"$namespace\", pool=\"G1 Survivor Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Used - {{job}} {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=~\"$namespace\", pool=\"G1 Survivor Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Committed - {{job}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{namespace=~\"$namespace\",pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{gc}} - {{job}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "{{gc}} - {{job}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=~\"$namespace\", pool=\"Metaspace\",pod_name=~\"$pod\"}",
     "legendFormat": "Max - {{job}} {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=~\"$namespace\", pool=\"Metaspace\",pod_name=~\"$pod\"}",
     "legendFormat": "Used - {{job}} {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=~\"$namespace\", pool=\"Metaspace\",pod_name=~\"$pod\"}",
     "legendFormat": "Committed - {{job}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=~\"$namespace\", pool=\"Compressed Class Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Max - {{job}} {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=~\"$namespace\", pool=\"Compressed Class Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Used - {{job}} {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=~\"$namespace\", pool=\"Compressed Class Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Committed - {{job}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{namespace=~\"$namespace\", pool=~\"CodeHeap.+\",pod_name=~\"$pod\"})",
     "legendFormat": "Used - {{job}} {{pod_name}}"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{namespace=~\"$namespace\", pool=\"CodeHeap.+\",pod_name=~\"$pod\"})",
     "legendFormat": "Committed - {{job}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "JVM current threads - {{job}} {{pod_name}}"
    },
    {
     "expr": "jvm_threads_daemon{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "JVM daemon threads - {{job}} {{pod_name}}"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "JVM deadlocked threads - {{job}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "loaded - {{job}} {{pod_name}}"
    },
    {
     "expr": "jvm_classes_unloaded_total{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "unloaded - {{job}} {{pod_name}}"
    }
   ]
  }
 ]
}