{
 "title": "spring-petclinic-easeagent",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GC times - G1 Young Generation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(application_jvm_gc_times{resource=\"G1 Young Generation\"}[1m:30s])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "GC collection time - G1 Young Generation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase((application_jvm_gc_total_collection_time{resource=\"G1 Young Generation\"})[1m:30s])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "GC G1-Eden-Space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(service) (application_jvm_memory_bytes_used{resource=\"pools.G1-Eden-Space\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "GC G1-Old-Space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(service) (application_jvm_memory_bytes_used{resource=\"pools.G1-Old-Gen\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "GC G1-Survivor-Space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(service) (application_jvm_memory_bytes_used{resource=\"pools.G1-Survivor-Space\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "GC G1-Metaspace-Space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(service) (application_jvm_memory_bytes_used{resource=\"pools.Metaspace\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Throughput for services",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sum by(url)(application_http_request_m1{service=\"api-gateway\"})[5m:30s])",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Total accessing count for services",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(avg by (url)(application_http_request_cnt{service=\"api-gateway\"})[5m:30s])",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "P99 for services",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sum by(url)(application_http_request_p99{service=\"api-gateway\"})[5m:30s])",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Latency P99 of services",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(avg by(service) (application_http_request_p99)[1m:1s])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Latency P95 of services",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(avg by(service) (application_http_request_p95)[5m:30s])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Latency P50 of services",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(avg by(service) (application_http_request_p50)[5m:30s])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Throughput m1 of services",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg_over_time(sum by(service) (application_http_request_m1)[5m:30s])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Throughput m5 of services",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 9, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg_over_time(sum by(service) (application_http_request_m5)[5m:30s])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Throughput m15 of services",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg_over_time(sum by(service) (application_http_request_m15)[5m:30s])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Avg SQL P99  Letency of Services",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(avg by (service) (application_jdbc_statement_p99)[5m:30s])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Avg SQL P50  Letency of Services",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 7, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(avg by (service) (application_jdbc_statement_p50)[5m:30s])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Avg SQL P95  Letency of Services",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(sum by (service) (application_jdbc_statement_p50)[1m:1s])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Average SQL m1 of the services",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg_over_time(sum by (service) (application_jdbc_statement_m1)[1m:1s])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Average SQL m5 of services",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg_over_time(sum by (service) (application_jdbc_statement_m5)[1m:1s])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Average SQL m15 of Service",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg_over_time(sum by (service) (application_jdbc_statement_m15)[15m:30s])",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}